### ISSUE TITLE
Please don't forget increasing versionCode

### ISSUE THREAD

**Issue by IzzySoft** [CYB3R-G0D/Calculator-app#3]
`versionCode` must be increased with each release, as that's what Android uses to tell versions apart. Your new v1.1.0 still has `versionCode: 1` – so it won't be offered as update to those already having v1.0.0 installed.

**Comment by CYB3R-G0D** [comment]
I made the *versionCode:* 2 now

**Comment by IzzySoft** [comment]
Thanks! Just remember to increase it with the next release(s) as well. As v1.1.0 has already been pulled, the next release will then "fix" it in my repo as well.

**Comment by CYB3R-G0D** [comment]
Yeah thank you for reminding me 😄
